command:
  uri: "http://ec2-18-222-29-23.us-east-2.compute.amazonaws.com:8080/command"
query:
  uri: "http://ec2-3-129-19-219.us-east-2.compute.amazonaws.com:8080/query"
## Logging ###
logging:
  level:
    root: ERROR
    #core: DEBUG
    org.apache.tomcat: DEBUG
    org.apache.catalina: DEBUG
    org.springframework.web: INFO
    com.iiht.fse4.skilltracker.composite: DEBUG
feign:
  hystrix:
    enabled: true

### Actuator ###
management:
  endpoint:
    health:
      show-details: "always"
  info:
    git:
      mode: "full"
  endpoints:
    web:
      ## Custom base path for Actuator
      base-path: /actuator
      exposure:
        include: "health,info"